### ISSUE TITLE
Emails receiving doesn't work if other addons have been added to the project

### ISSUE THREAD

**Issue by imorenov94** [Haulmont/jmix-imap#18]
**Environment:**
Jmix version: 1.0.2

Steps:
1. Clone [project](https://github.com/jmix-projects/sample-sales-jmix/tree/with_some_addons) from with_some_addons branch
2. Run the app
3. Create a new configuration for IMAP
4. Open IMAP Message browser
**ER:** emails should be download by the scheduler into the browser
**AR:** emails haven't been downloaded 
**WA:** For projects without any addons IMAP works correctly

**Comment by m-orlova** [comment]
@imorenov94 It is not a bug. Mailboxes are synchronized by a system user, so the system user should have an access to the ImapMailBox entity to load mailboxes from a database. But in this project the system user does not have any granted authority, so that's why it does not have access to the ImapMailBox entity. For new projects, Jmix studio generates DatabaseUserRepository that overrides the 'initSystemUser' method in which granted authority with full access role is set for system user.
